version: '3'

services:
  localhost:
    image: postgres:11.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  django_app:
    build: .
    volumens:
      - static:/code/static
      - .:/code
    depends_on:
      - localhost

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - django_app
  
  volumens:
    .:
    localhost:
    static: