# Generated by Django 4.0.2 on 2022-03-08 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('c207_id_experience', models.AutoField(primary_key=True, serialize=False)),
                ('c207_description', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'db_table': 'c207_experience',
            },
        ),
        migrations.CreateModel(
            name='Status_Vacant',
            fields=[
                ('c204_id_status', models.AutoField(primary_key=True, serialize=False)),
                ('c204_description', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name': 'Status_Vacant',
                'verbose_name_plural': 'Status_Vacants',
                'db_table': 'c204_status_vacant',
            },
        ),
        migrations.CreateModel(
            name='Type_Candidate',
            fields=[
                ('c206_id_type', models.AutoField(primary_key=True, serialize=False)),
                ('c206_description', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name': 'Type_Candidate',
                'verbose_name_plural': 'Type_Candidates',
                'db_table': 'c206_type_candidate',
            },
        ),
        migrations.CreateModel(
            name='Vacant',
            fields=[
                ('t200_id_vacant', models.AutoField(primary_key=True, serialize=False)),
                ('t200_job', models.CharField(max_length=50)),
                ('t200_description', models.TextField()),
                ('t200_address', models.TextField()),
                ('t200_check_time', models.DateField()),
                ('t200_closing_hour', models.DateField()),
                ('t200_work_days', models.CharField(max_length=7)),
                ('t200_benefits', models.TextField()),
                ('t200_min_salary', models.IntegerField()),
                ('t200_max_salary', models.IntegerField()),
                ('t200_gross_salary', models.BooleanField()),
                ('t200_home_ofice', models.BooleanField()),
                ('t200_open_date', models.DateField()),
                ('t200_close_date', models.DateField()),
                ('c106_id_type_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.type_candidate')),
                ('c204_id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.status_vacant')),
                ('c207_id_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.experience')),
            ],
            options={
                'verbose_name': 'Vacant',
                'verbose_name_plural': 'Vacants',
                'db_table': 'c200_vacant',
            },
        ),
    ]
