# Generated by Django 4.0.2 on 2022-03-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacant',
            name='c106_id_type_candidate',
        ),
        migrations.RemoveField(
            model_name='vacant',
            name='c204_id_status',
        ),
        migrations.RemoveField(
            model_name='vacant',
            name='c207_id_experience',
        ),
    ]
