# Generated by Django 4.0.2 on 2022-03-15 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_academiclevel_academicstate_plataform_skills_and_more'),
        ('vacantes', '0002_remove_vacant_c106_id_type_candidate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('t202_id_announcement', models.AutoField(primary_key=True, serialize=False)),
                ('t202_announcement', models.FileField(upload_to='')),
                ('T202_description', models.TextField()),
                ('t202_publish_date', models.DateField(null=True)),
                ('t202_close_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Annuncement',
                'verbose_name_plural': 'Annuncements',
                'db_table': 't202_comunicados',
            },
        ),
        migrations.CreateModel(
            name='ApplicationState',
            fields=[
                ('c205_id_application_state', models.AutoField(primary_key=True, serialize=False)),
                ('c205_description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'ApplicationState',
                'db_table': 'c205_estado_solicitud',
            },
        ),
        migrations.CreateModel(
            name='ReportState',
            fields=[
                ('c220_id_report_state', models.AutoField(primary_key=True, serialize=False)),
                ('c220_description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'ReporteState',
                'db_table': 'c220_estado_reporte',
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('c210_id_report_type', models.AutoField(primary_key=True, serialize=False)),
                ('c210_description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'ReportType',
                'db_table': 'c210_tipo_reporte',
            },
        ),
        migrations.RenameModel(
            old_name='Type_Candidate',
            new_name='CandidateProfile',
        ),
        migrations.RenameModel(
            old_name='Status_Vacant',
            new_name='VacantStatus',
        ),
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'verbose_name': 'CandidateProfile'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experience'},
        ),
        migrations.AlterModelOptions(
            name='vacantstatus',
            options={'verbose_name': 'Vacant status'},
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='c206_id_type',
            new_name='c206_id_profile',
        ),
        migrations.RenameField(
            model_name='vacant',
            old_name='t200_open_date',
            new_name='t200_publish_date',
        ),
        migrations.RemoveField(
            model_name='vacant',
            name='t200_address',
        ),
        migrations.RemoveField(
            model_name='vacant',
            name='t200_benefits',
        ),
        migrations.AlterField(
            model_name='vacant',
            name='t200_job',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterModelTable(
            name='candidateprofile',
            table='c206_perfil_candidato',
        ),
        migrations.AlterModelTable(
            name='experience',
            table='c207_experiencia',
        ),
        migrations.AlterModelTable(
            name='vacantstatus',
            table='c204_estado_vacante',
        ),
        migrations.CreateModel(
            name='Ubication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t213_state', models.CharField(default='No definido', max_length=30)),
                ('t213_mucipality', models.CharField(default='No definido', max_length=70)),
                ('t213_locality', models.CharField(default='No definido', max_length=100)),
                ('t213_street', models.CharField(blank=True, max_length=60, null=True)),
                ('t213_cp', models.IntegerField(blank=True, null=True)),
                ('t213_interior_number', models.CharField(blank=True, max_length=20, null=True)),
                ('t213_exterior_number', models.CharField(blank=True, max_length=20, null=True)),
                ('t200_id_vacant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ApplicationUbication', to='vacantes.vacant')),
            ],
            options={
                'verbose_name': 'Ubication',
                'db_table': 't213_ubicacion',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('t203_id_report', models.AutoField(primary_key=True, serialize=False)),
                ('t203_publish_type', models.BooleanField(default=True)),
                ('t203_report_date', models.DateField(null=True)),
                ('t203_atention_date', models.DateField(null=True)),
                ('t203_adittional_comment', models.TextField(blank=True, null=True)),
                ('t100_boleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportStudent', to='students.student')),
                ('t200_id_vacant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Report', to='vacantes.vacant')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 't203_reportes',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('t201_id_application', models.AutoField(primary_key=True, serialize=False)),
                ('t201_cv', models.FileField(blank=True, null=True, upload_to='')),
                ('t201_date_application', models.DateField()),
                ('t100_boleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AppliedStudent', to='students.student')),
                ('t200_id_vacant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentApplication', to='vacantes.vacant')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'c201_application',
            },
        ),
    ]
