# Generated by Django 4.0.2 on 2022-03-16 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0003_announcement_applicationstate_reportstate_reporttype_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='application',
            table='t201_application',
        ),
        migrations.AlterModelTable(
            name='vacant',
            table='t200_vacant',
        ),
    ]
