export const POST_NEW_JOB = Object.freeze({
  t200_id_vacant:null,
  t200_job:null,
  t200_publish_date:null,
  t200_close_date:null,
  t200_interior_number:"",
  t200_exterior_number:"",
  t200_vacancy:"",
  t200_min_salary: "",
  t200_max_salary: "",
  t200_working_hours: "",
  t300_id_company:null,
  c207_id_experience:null,
  c214_id_modality:null,
  c206_id_profile:null,
  c222_id_locality:null,
  c208_id_contract:null,
  mandatory_level: ["Medio","Avanzado"],
  optional_level: ["Medio","Avanzado"],
  language_level: ["80"],
});
