# Generated by Django 4.0.2 on 2022-03-03 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('t100_boleta', models.PositiveIntegerField(help_text='id unico para este alumno', primary_key=True, serialize=False)),
                ('t100_name', models.CharField(max_length=50)),
                ('t100_last_name', models.CharField(max_length=50)),
                ('t100_username', models.CharField(max_length=40)),
                ('t100_password', models.CharField(max_length=100)),
                ('t100_rfc', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('t100_nss', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('t100_cv', models.FileField(blank=True, null=True, upload_to='')),
                ('t100_email', models.EmailField(max_length=50)),
                ('t100_gender', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1, null=True)),
                ('t100_academic_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('t100_date_of_birth', models.DateField(blank=True, null=True)),
                ('t100_travel', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'unique_together': {('t100_boleta', 't100_email')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('t102_id_skill', models.AutoField(primary_key=True, serialize=False)),
                ('t102_description', models.CharField(max_length=100)),
                ('t100_boleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='students.student')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
