# Generated by Django 4.0.2 on 2022-03-19 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('c107_id_academic_level', models.AutoField(primary_key=True, serialize=False)),
                ('c107_description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'AcademicLevel',
                'db_table': 'c107_nivel_academico',
            },
        ),
        migrations.CreateModel(
            name='AcademicState',
            fields=[
                ('c109_id_academic_state', models.AutoField(primary_key=True, serialize=False)),
                ('c109_description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'AcademicState',
                'db_table': 'c109_estado_academico',
            },
        ),
        migrations.CreateModel(
            name='Lenguage',
            fields=[
                ('c111_id_lenguage', models.AutoField(primary_key=True, serialize=False)),
                ('c111_description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Lenguange',
                'verbose_name_plural': 'Lenguages',
                'db_table': 'c111_idiomas',
            },
        ),
        migrations.CreateModel(
            name='Plataform',
            fields=[
                ('c115_id_plataform', models.AutoField(primary_key=True, serialize=False)),
                ('c115_description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Plataform',
                'verbose_name_plural': 'Plataforms',
                'db_table': 'c115_plataformas',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('c116_id_skill', models.AutoField(primary_key=True, serialize=False)),
                ('c116_description', models.CharField(max_length=60)),
                ('c116_type', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'c116_habilidades',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('t100_boleta', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('t100_name', models.CharField(max_length=50)),
                ('t100_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('t100_username', models.CharField(blank=True, max_length=40, null=True)),
                ('t100_password', models.CharField(max_length=100)),
                ('t100_cv', models.FileField(blank=True, null=True, upload_to='')),
                ('t100_email', models.EmailField(max_length=50)),
                ('t100_gender', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1, null=True)),
                ('t100_date_of_birth', models.DateField(blank=True, null=True)),
                ('t100_travel', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 't100_alumno',
                'unique_together': {('t100_boleta', 't100_email')},
            },
        ),
        migrations.CreateModel(
            name='StudyArea',
            fields=[
                ('c108_id_study_area', models.AutoField(primary_key=True, serialize=False)),
                ('c108_study_area', models.CharField(max_length=60)),
                ('c108_generic_carreer', models.CharField(max_length=100)),
                ('c108_specific_carreer', models.CharField(max_length=100)),
                ('c108_description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'StudyArea',
                'db_table': 'c108_area_estudio',
            },
        ),
        migrations.CreateModel(
            name='residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t101_state', models.CharField(blank=True, choices=[('AGUASCALIENTES', 'AGUASCALIENTES'), ('BAJA CALIFORNIA', 'BAJA CALIFORNIA'), ('BAJA CALIFORNIA SUR', 'BAJA CALIFORNIA SUR'), ('CAMPECHE', 'CAMPECHE'), ('COAHUILA', 'COAHUILA'), ('COLIMA', 'COLIMA'), ('CHIAPAS', 'CHIAPAS'), ('CHIHUAHUA', 'CHIHUAHUA'), ('CIUDAD DE MEXICO', 'CIUDAD DE MEXICO'), ('DURANGO', 'DURANGO'), ('GUANAJUATO', 'GUANAJUATO'), ('GUERRERO', 'GUERRERO'), ('HIDALGO', 'HIDALGO'), ('JALISCO', 'JALISCO'), ('MEXICO', 'MEXICO'), ('MICHOACAN', 'MICHOACAN'), ('MORELOS', 'MORELOS'), ('NAYARIT', 'NAYARIT'), ('NUEVO LEON', 'NUEVO LEON'), ('OAXACA', 'OAXACA'), ('PUEBLA', 'PUEBLA'), ('QUERETARO DE ARTEAGA', 'QUERETARO DE ARTEAGA'), ('QUINTANA ROO', 'QUINTANA ROO'), ('SAN LUIS POTOSI', 'SAN LUIS POTOSI'), ('SINALOA', 'SINALOA'), ('SONORA', 'SONORA'), ('TABASCO', 'TABASCO'), ('TAMAULIPAS', 'TAMAULIPAS'), ('TLAXCALA', 'TLAXCALA'), ('VERACRUZ', 'VERACRUZ '), ('YUCATAN', 'YUCATAN'), ('ZACATECAS', 'ZACATECAS'), ('NO ESPECIFICADA', 'NO ESPECIFICADA')], default='33', max_length=50, null=True)),
                ('t101_municipality', models.CharField(blank=True, max_length=70, null=True)),
                ('t101_locality', models.CharField(blank=True, max_length=100, null=True)),
                ('t100_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentResidence', to='students.student', unique=True)),
            ],
            options={
                'verbose_name': 'Residence',
                'db_table': 't101_domicilio',
            },
        ),
        migrations.CreateModel(
            name='InterestArea',
            fields=[
                ('t113_id_registrer', models.AutoField(primary_key=True, serialize=False)),
                ('t100_boleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentInterests', to='students.student')),
            ],
            options={
                'verbose_name': 'Areas of interest',
                'db_table': 't113_areas_interes',
            },
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('t102_id_skill_registrer', models.AutoField(primary_key=True, serialize=False)),
                ('c116_id_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SkillDescription', to='students.skills')),
                ('t100_boleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentSkills', to='students.student')),
            ],
            options={
                'verbose_name': 'StudentSkill',
                'verbose_name_plural': 'StudentSkills',
                'db_table': 't102_habilidades',
                'unique_together': {('t100_boleta', 'c116_id_skill')},
            },
        ),
        migrations.CreateModel(
            name='StudentLenguage',
            fields=[
                ('t110_id_registrer', models.AutoField(primary_key=True, serialize=False)),
                ('t110_written_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('t110_reading_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('t110_speaking_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('t110_comprension_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('t110_native', models.BooleanField(default=False)),
                ('c111_id_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LenguageDescription', to='students.lenguage')),
                ('t100_boleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentLenguages', to='students.student')),
            ],
            options={
                'verbose_name': 'StudentLenguage',
                'verbose_name_plural': 'StudentLenguages',
                'db_table': 't110_idiomas',
                'unique_together': {('t100_boleta', 'c111_id_language')},
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('t114_id_registrer', models.AutoField(primary_key=True, serialize=False)),
                ('t113_link', models.CharField(blank=True, max_length=100, null=True)),
                ('c115_id_plataform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlataformDescription', to='students.plataform')),
                ('t100_boleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentLinks', to='students.student')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'db_table': 't114_enlaces',
                'unique_together': {('t100_boleta', 'c115_id_plataform')},
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('t103_id_registrer', models.AutoField(primary_key=True, serialize=False)),
                ('t103_corporation', models.CharField(blank=True, max_length=80, null=True)),
                ('t103_employment', models.CharField(blank=True, max_length=80, null=True)),
                ('t103_description', models.TextField()),
                ('t103_start_date', models.DateField(null=True)),
                ('t103_end_date', models.DateField(null=True)),
                ('t100_boleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentEmployments', to='students.student')),
            ],
            options={
                'verbose_name': 'Employment history',
                'db_table': 't103_historial_laboral',
                'unique_together': {('t100_boleta', 't103_corporation')},
            },
        ),
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('t104_id_registrer', models.AutoField(primary_key=True, serialize=False)),
                ('t104_academic_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('t104_carreer', models.CharField(blank=True, max_length=100, null=True)),
                ('t104_start_date', models.DateField(blank=True, null=True)),
                ('t104_end_date', models.DateField(blank=True, null=True)),
                ('t100_boleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentAcademics', to='students.student')),
            ],
            options={
                'verbose_name': 'Academic history',
                'db_table': 't104_historial_academico',
                'unique_together': {('t100_boleta', 't104_carreer')},
            },
        ),
    ]
