# Generated by Django 4.0.2 on 2022-03-19 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('c116_id_skill', models.AutoField(primary_key=True, serialize=False)),
                ('c116_description', models.CharField(max_length=60)),
                ('c116_type', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'c116_habilidades',
            },
        ),
        migrations.DeleteModel(
            name='StudentSkills',
        ),
        migrations.AddField(
            model_name='studentskill',
            name='c116_id_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SkillDescription', to='students.skills'),
        ),
    ]
