# Generated by Django 4.0.2 on 2022-03-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('c107_id_academic_level', models.AutoField(primary_key=True, serialize=False)),
                ('c107_description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'AcademicLevel',
                'db_table': 'c107_nivel_academico',
            },
        ),
        migrations.CreateModel(
            name='AcademicState',
            fields=[
                ('c109_id_academic_state', models.AutoField(primary_key=True, serialize=False)),
                ('c109_description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'AcademicState',
                'db_table': 'c109_estado_academico',
            },
        ),
        migrations.CreateModel(
            name='Plataform',
            fields=[
                ('c115_id_plataform', models.AutoField(primary_key=True, serialize=False)),
                ('c115_description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Plataform',
                'verbose_name_plural': 'Plataforms',
                'db_table': 'c115_plataformas',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('c116_id_skill', models.AutoField(primary_key=True, serialize=False)),
                ('c116_description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'c116_habilidades',
            },
        ),
        migrations.CreateModel(
            name='StudyArea',
            fields=[
                ('c108_id_study_area', models.AutoField(primary_key=True, serialize=False)),
                ('c108_description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'StudyArea',
                'db_table': 'c108_area_estudio',
            },
        ),
        migrations.RenameModel(
            old_name='Lenguage',
            new_name='StudentLenguage',
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='StudentSkill',
        ),
        migrations.AlterModelOptions(
            name='studentlenguage',
            options={'verbose_name': 'StudentLenguage', 'verbose_name_plural': 'StudentLenguages'},
        ),
        migrations.AlterModelOptions(
            name='studentskill',
            options={'verbose_name': 'StudentSkill', 'verbose_name_plural': 'StudentSkills'},
        ),
        migrations.AlterModelTable(
            name='studentskill',
            table='t102_habilidades',
        ),
    ]
