# Generated by Django 4.0.2 on 2022-03-07 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='t100_boleta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='students.student'),
        ),
    ]
