# Generated by Django 4.0.2 on 2022-03-19 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_t102_id_skill_registrer_studentskill_t102_id_registrer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='c115_id_plataform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PlataformDescription', to='students.plataform'),
        ),
    ]
