# Generated by Django 4.0.2 on 2022-03-07 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_skill_t100_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='t100_boleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='students.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='t100_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='t100_username',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
