# Generated by Django 4.0.2 on 2022-03-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_academiclevel_academicstate_plataform_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='t100_nss',
        ),
        migrations.RemoveField(
            model_name='student',
            name='t100_rfc',
        ),
        migrations.RemoveField(
            model_name='studentskill',
            name='t102_description',
        ),
    ]
