# Generated by Django 4.0.2 on 2022-03-19 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_link_c115_id_plataform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlenguage',
            name='c111_id_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='LenguageDescription', to='students.lenguage'),
        ),
    ]
