# Generated by Django 4.0.2 on 2022-03-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_t100_nss_remove_student_t100_rfc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residence',
            old_name='t101_mucipality',
            new_name='t101_municipality',
        ),
    ]
