# Generated by Django 4.0.2 on 2022-03-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_skill_t100_boleta_alter_student_t100_last_name_and_more'),
        ('students', '0004_rename_t101_mucipality_residence_t101_municipality'),
    ]

    operations = [
    ]
